package newmoviebay.mncplaymedia.com.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_newcontent{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("putama").vw.setLeft((int)(0d));
views.get("putama").vw.setWidth((int)((100d / 100 * width) - (0d)));
views.get("putama").vw.setTop((int)(0d));
views.get("putama").vw.setHeight((int)((100d / 100 * height) - (0d)));
views.get("patas").vw.setLeft((int)(0d));
views.get("patas").vw.setWidth((int)((100d / 100 * width) - (0d)));
views.get("patas").vw.setTop((int)(0d));
views.get("patas").vw.setHeight((int)((10d / 100 * height) - (0d)));
views.get("plogo").vw.setLeft((int)((views.get("ivback").vw.getLeft() + views.get("ivback").vw.getWidth())+(5d / 100 * width)));
views.get("plogo").vw.setWidth((int)((80d / 100 * width) - ((views.get("ivback").vw.getLeft() + views.get("ivback").vw.getWidth())+(5d / 100 * width))));
views.get("plogo").vw.setTop((int)((1d / 100 * height)));
views.get("plogo").vw.setHeight((int)((10d / 100 * height) - ((1d / 100 * height))));
views.get("ivback").vw.setLeft((int)((2d / 100 * width)));
views.get("ivback").vw.setWidth((int)((views.get("plogo").vw.getLeft())-(4d / 100 * width) - ((2d / 100 * width))));
views.get("ivback").vw.setTop((int)((5d / 100 * width)));
views.get("lbljudul").vw.setLeft((int)(0d));
views.get("lbljudul").vw.setWidth((int)((68d / 100 * width) - (0d)));
views.get("lbljudul").vw.setTop((int)(0d));
views.get("lbljudul").vw.setHeight((int)((views.get("lblcate").vw.getTop())+(1d / 100 * height) - (0d)));
views.get("lblcate").vw.setLeft((int)(0d));
views.get("lblcate").vw.setWidth((int)((68d / 100 * width) - (0d)));
views.get("lblcate").vw.setTop((int)((views.get("lbljudul").vw.getTop() + views.get("lbljudul").vw.getHeight())-(1d / 100 * height)));
views.get("lblcate").vw.setHeight((int)((10d / 100 * height) - ((views.get("lbljudul").vw.getTop() + views.get("lbljudul").vw.getHeight())-(1d / 100 * height))));
views.get("ivshare").vw.setLeft((int)((views.get("lbljudul").vw.getLeft() + views.get("lbljudul").vw.getWidth())+(5d / 100 * width)));
views.get("ivshare").vw.setLeft((int)((98d / 100 * width) - (views.get("ivshare").vw.getWidth())));
views.get("ivshare").vw.setTop((int)((5d / 100 * width)));
views.get("pivmovies").vw.setLeft((int)(0d));
views.get("pivmovies").vw.setWidth((int)((100d / 100 * width) - (0d)));
views.get("pivmovies").vw.setTop((int)((views.get("patas").vw.getTop() + views.get("patas").vw.getHeight())));
views.get("pivmovies").vw.setHeight((int)((34d / 100 * height) - ((views.get("patas").vw.getTop() + views.get("patas").vw.getHeight()))));
views.get("ivmovies").vw.setLeft((int)(0d));
views.get("ivmovies").vw.setWidth((int)((100d / 100 * width) - (0d)));
views.get("ivmovies").vw.setTop((int)(0d));
views.get("ivmovies").vw.setHeight((int)((30d / 100 * height) - (0d)));
views.get("ivplay").vw.setLeft((int)((38d / 100 * width)));
views.get("ivplay").vw.setWidth((int)((60d / 100 * width) - ((38d / 100 * width))));
views.get("ivplay").vw.setTop((int)((5d / 100 * height)));
views.get("ivplay").vw.setHeight((int)((14d / 100 * height) - ((5d / 100 * height))));
views.get("psemua").vw.setTop((int)((16d / 100 * height)));
views.get("psemua").vw.setHeight((int)((25d / 100 * height) - ((16d / 100 * height))));
views.get("psemua").vw.setLeft((int)(0d));
views.get("psemua").vw.setWidth((int)((100d / 100 * width) - (0d)));
views.get("ivtrailer").vw.setTop((int)((2d / 100 * height)));
views.get("ivtrailer").vw.setHeight((int)((6d / 100 * height) - ((2d / 100 * height))));
views.get("ivtrailer").vw.setLeft((int)((4d / 100 * width)));
views.get("ivtrailer").vw.setWidth((int)((views.get("lbltrailer").vw.getLeft())-(1d / 100 * width) - ((4d / 100 * width))));
views.get("lbltrailer").vw.setLeft((int)((views.get("ivtrailer").vw.getLeft() + views.get("ivtrailer").vw.getWidth())+(1d / 100 * width)));
views.get("lbltrailer").vw.setWidth((int)((25d / 100 * height) - ((views.get("ivtrailer").vw.getLeft() + views.get("ivtrailer").vw.getWidth())+(1d / 100 * width))));
views.get("lbltrailer").vw.setTop((int)((2d / 100 * height)));
views.get("lbltrailer").vw.setHeight((int)((6d / 100 * height) - ((2d / 100 * height))));
views.get("ivrate").vw.setTop((int)((2d / 100 * height)));
views.get("ivrate").vw.setHeight((int)((6d / 100 * height) - ((2d / 100 * height))));
views.get("ivrate").vw.setLeft((int)((views.get("lbltrailer").vw.getLeft() + views.get("lbltrailer").vw.getWidth())+(1d / 100 * width)));
views.get("ivrate").vw.setWidth((int)((views.get("lblrat").vw.getLeft())-(3d / 100 * width) - ((views.get("lbltrailer").vw.getLeft() + views.get("lbltrailer").vw.getWidth())+(1d / 100 * width))));
views.get("lblrat").vw.setLeft((int)((views.get("ivrate").vw.getLeft() + views.get("ivrate").vw.getWidth())+(1d / 100 * width)));
views.get("lblrat").vw.setWidth((int)((views.get("ivcomment").vw.getLeft())-(1d / 100 * width) - ((views.get("ivrate").vw.getLeft() + views.get("ivrate").vw.getWidth())+(1d / 100 * width))));
views.get("lblrat").vw.setTop((int)((2d / 100 * height)));
views.get("lblrat").vw.setHeight((int)((6d / 100 * height) - ((2d / 100 * height))));
views.get("pinfo").vw.setLeft((int)(0d));
views.get("pinfo").vw.setWidth((int)((100d / 100 * width) - (0d)));
views.get("pinfo").vw.setTop((int)((views.get("pivmovies").vw.getTop() + views.get("pivmovies").vw.getHeight())+(0d / 100 * height)));
views.get("pinfo").vw.setHeight((int)((100d / 100 * height) - ((views.get("pivmovies").vw.getTop() + views.get("pivmovies").vw.getHeight())+(0d / 100 * height))));
views.get("lbltitle").vw.setLeft((int)((5d / 100 * width)));
views.get("lbltitle").vw.setWidth((int)((80d / 100 * width) - ((5d / 100 * width))));
views.get("lbltitle").vw.setTop((int)((2d / 100 * height)));
views.get("ivtake").vw.setLeft((int)((5d / 100 * width)));
views.get("ivtake").vw.setWidth((int)((12d / 100 * width) - ((5d / 100 * width))));
views.get("ivtake").vw.setTop((int)((views.get("lbltitle").vw.getTop() + views.get("lbltitle").vw.getHeight())+(1d / 100 * height)));
views.get("ivwatch").vw.setLeft((int)((5d / 100 * width)));
views.get("ivwatch").vw.setWidth((int)((12d / 100 * width) - ((5d / 100 * width))));
views.get("ivwatch").vw.setTop((int)((views.get("ivtake").vw.getTop() + views.get("ivtake").vw.getHeight())+(1d / 100 * height)));
views.get("ivwatch").vw.setHeight((int)((views.get("ivgaris").vw.getTop())+(1d / 100 * height) - ((views.get("ivtake").vw.getTop() + views.get("ivtake").vw.getHeight())+(1d / 100 * height))));
views.get("lbltake").vw.setLeft((int)((views.get("ivtake").vw.getLeft() + views.get("ivtake").vw.getWidth())+(1d / 100 * width)));
views.get("lbltake").vw.setWidth((int)((50d / 100 * width) - ((views.get("ivtake").vw.getLeft() + views.get("ivtake").vw.getWidth())+(1d / 100 * width))));
views.get("lbltake").vw.setTop((int)((views.get("lbltitle").vw.getTop() + views.get("lbltitle").vw.getHeight())+(1d / 100 * height)));
views.get("lblwatch").vw.setLeft((int)((views.get("ivwatch").vw.getLeft() + views.get("ivwatch").vw.getWidth())+(1d / 100 * width)));
views.get("lblwatch").vw.setWidth((int)((50d / 100 * width) - ((views.get("ivwatch").vw.getLeft() + views.get("ivwatch").vw.getWidth())+(1d / 100 * width))));
views.get("lblwatch").vw.setTop((int)((views.get("lbltake").vw.getTop() + views.get("lbltake").vw.getHeight())+(1d / 100 * height)));
views.get("ivgaris").vw.setLeft((int)((5d / 100 * width)));
views.get("ivgaris").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("ivgaris").vw.setTop((int)((views.get("lblwatch").vw.getTop() + views.get("lblwatch").vw.getHeight())+(1d / 100 * height)));
views.get("lblrate").vw.setLeft((int)((80d / 100 * width)));
views.get("lblrate").vw.setWidth((int)((95d / 100 * width) - ((80d / 100 * width))));
views.get("lblrate").vw.setTop((int)((8d / 100 * height)));
views.get("lblrate").vw.setHeight((int)((views.get("ivgaris").vw.getTop())-(2d / 100 * height) - ((8d / 100 * height))));
views.get("lbldir").vw.setLeft((int)((5d / 100 * width)));
views.get("lbldir").vw.setWidth((int)((20d / 100 * width) - ((5d / 100 * width))));
views.get("lbldir").vw.setTop((int)((views.get("ivgaris").vw.getTop() + views.get("ivgaris").vw.getHeight())+(1d / 100 * height)));
views.get("lbldir").vw.setHeight((int)((views.get("lblcast").vw.getTop())+(4d / 100 * height) - ((views.get("ivgaris").vw.getTop() + views.get("ivgaris").vw.getHeight())+(1d / 100 * height))));
views.get("lblcast").vw.setLeft((int)((5d / 100 * width)));
views.get("lblcast").vw.setWidth((int)((20d / 100 * width) - ((5d / 100 * width))));
views.get("lblcast").vw.setTop((int)((views.get("lbldir").vw.getTop() + views.get("lbldir").vw.getHeight())+(2d / 100 * height)));
views.get("lblcast").vw.setHeight((int)((views.get("lblwrite").vw.getTop()) - ((views.get("lbldir").vw.getTop() + views.get("lbldir").vw.getHeight())+(2d / 100 * height))));
views.get("lblwrite").vw.setLeft((int)((5d / 100 * width)));
views.get("lblwrite").vw.setWidth((int)((20d / 100 * width) - ((5d / 100 * width))));
views.get("lblwrite").vw.setTop((int)((views.get("lblcast").vw.getTop() + views.get("lblcast").vw.getHeight())+(3d / 100 * height)));
views.get("lblwrite").vw.setHeight((int)((views.get("lblsynopsis").vw.getTop())+(2d / 100 * height) - ((views.get("lblcast").vw.getTop() + views.get("lblcast").vw.getHeight())+(3d / 100 * height))));
views.get("lblnmdir").vw.setLeft((int)((views.get("lbldir").vw.getLeft() + views.get("lbldir").vw.getWidth())+(1d / 100 * width)));
views.get("lblnmdir").vw.setWidth((int)((50d / 100 * width) - ((views.get("lbldir").vw.getLeft() + views.get("lbldir").vw.getWidth())+(1d / 100 * width))));
views.get("lblnmdir").vw.setTop((int)((views.get("ivgaris").vw.getTop() + views.get("ivgaris").vw.getHeight())+(1d / 100 * height)));
views.get("lblnmcast").vw.setLeft((int)((views.get("lblcast").vw.getLeft() + views.get("lblcast").vw.getWidth())+(1d / 100 * width)));
views.get("lblnmcast").vw.setWidth((int)((50d / 100 * width) - ((views.get("lblcast").vw.getLeft() + views.get("lblcast").vw.getWidth())+(1d / 100 * width))));
views.get("lblnmcast").vw.setTop((int)((views.get("lblnmdir").vw.getTop() + views.get("lblnmdir").vw.getHeight())+(1d / 100 * height)));
views.get("lblnmwrite").vw.setLeft((int)((views.get("lblwrite").vw.getLeft() + views.get("lblwrite").vw.getWidth())+(1d / 100 * width)));
views.get("lblnmwrite").vw.setWidth((int)((50d / 100 * width) - ((views.get("lblwrite").vw.getLeft() + views.get("lblwrite").vw.getWidth())+(1d / 100 * width))));
views.get("lblnmwrite").vw.setTop((int)((views.get("lblnmcast").vw.getTop() + views.get("lblnmcast").vw.getHeight())+(1d / 100 * height)));
views.get("lblsynopsis").vw.setLeft((int)((5d / 100 * width)));
views.get("lblsynopsis").vw.setWidth((int)((50d / 100 * width) - ((5d / 100 * width))));
views.get("lblsynopsis").vw.setTop((int)((views.get("lblnmwrite").vw.getTop() + views.get("lblnmwrite").vw.getHeight())+(1d / 100 * height)));
views.get("lblsynopsis").vw.setHeight((int)((views.get("lblallsyn").vw.getTop())+(4d / 100 * height) - ((views.get("lblnmwrite").vw.getTop() + views.get("lblnmwrite").vw.getHeight())+(1d / 100 * height))));
views.get("lblallsyn").vw.setLeft((int)((5d / 100 * width)));
views.get("lblallsyn").vw.setWidth((int)((100d / 100 * width) - ((5d / 100 * width))));
views.get("lblallsyn").vw.setTop((int)((views.get("lblsynopsis").vw.getTop() + views.get("lblsynopsis").vw.getHeight())+(1d / 100 * height)));
views.get("lblallsyn").vw.setHeight((int)((70d / 100 * height) - ((views.get("lblsynopsis").vw.getTop() + views.get("lblsynopsis").vw.getHeight())+(1d / 100 * height))));

}
}