package newmoviebay.mncplaymedia.com.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_newcontents{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("putama").vw.setLeft((int)(0d));
views.get("putama").vw.setWidth((int)((100d / 100 * width) - (0d)));
views.get("putama").vw.setTop((int)(0d));
views.get("putama").vw.setHeight((int)((100d / 100 * height) - (0d)));
views.get("patas").vw.setLeft((int)(0d));
views.get("patas").vw.setWidth((int)((100d / 100 * width) - (0d)));
views.get("patas").vw.setTop((int)(0d));
views.get("patas").vw.setHeight((int)((12d / 100 * height) - (0d)));
views.get("ivback").vw.setLeft((int)((4d / 100 * width)));
views.get("ivback").vw.setWidth((int)((views.get("pnama").vw.getLeft())-(2d / 100 * width) - ((4d / 100 * width))));
views.get("ivback").vw.setTop((int)((2d / 100 * height)));
views.get("ivback").vw.setHeight((int)((8d / 100 * height) - ((2d / 100 * height))));
views.get("ivshared").vw.setLeft((int)((views.get("pnama").vw.getLeft() + views.get("pnama").vw.getWidth())+(30d / 100 * width)));
views.get("ivshared").vw.setWidth((int)((100d / 100 * width) - ((views.get("pnama").vw.getLeft() + views.get("pnama").vw.getWidth())+(30d / 100 * width))));
views.get("ivshared").vw.setTop((int)((2d / 100 * height)));
views.get("ivshared").vw.setHeight((int)((8d / 100 * height) - ((2d / 100 * height))));
views.get("pnama").vw.setLeft((int)((views.get("ivback").vw.getLeft() + views.get("ivback").vw.getWidth())+(16d / 100 * width)));
views.get("pnama").vw.setWidth((int)((views.get("ivshared").vw.getLeft())-(6d / 100 * width) - ((views.get("ivback").vw.getLeft() + views.get("ivback").vw.getWidth())+(16d / 100 * width))));
views.get("pnama").vw.setTop((int)((2d / 100 * height)));
views.get("pnama").vw.setHeight((int)((10d / 100 * height) - ((2d / 100 * height))));
views.get("pbawah").vw.setLeft((int)(0d));
views.get("pbawah").vw.setWidth((int)((100d / 100 * width) - (0d)));
views.get("pbawah").vw.setTop((int)((views.get("pmovies").vw.getTop() + views.get("pmovies").vw.getHeight())+(4d / 100 * height)));
views.get("pbawah").vw.setHeight((int)((100d / 100 * height) - ((views.get("pmovies").vw.getTop() + views.get("pmovies").vw.getHeight())+(4d / 100 * height))));
views.get("pmovies").vw.setLeft((int)(0d));
views.get("pmovies").vw.setWidth((int)((100d / 100 * width) - (0d)));
views.get("pmovies").vw.setTop((int)((views.get("patas").vw.getTop() + views.get("patas").vw.getHeight())));
views.get("pmovies").vw.setHeight((int)((views.get("pbawah").vw.getTop()) - ((views.get("patas").vw.getTop() + views.get("patas").vw.getHeight()))));
views.get("ivmovie").vw.setLeft((int)(0d));
views.get("ivmovie").vw.setWidth((int)((100d / 100 * width) - (0d)));
views.get("ivmovie").vw.setTop((int)(0d));
views.get("ivmovie").vw.setHeight((int)((31.5d / 100 * height) - (0d)));
views.get("ivplay").vw.setLeft((int)((38d / 100 * width)));
views.get("ivplay").vw.setWidth((int)((60d / 100 * width) - ((38d / 100 * width))));
views.get("ivplay").vw.setTop((int)((3d / 100 * height)));
views.get("ivplay").vw.setHeight((int)((16d / 100 * height) - ((3d / 100 * height))));
views.get("pmenu").vw.setLeft((int)(0d));
views.get("pmenu").vw.setWidth((int)((100d / 100 * width) - (0d)));
views.get("pmenu").vw.setTop((int)((22d / 100 * height)));
views.get("pmenu").vw.setHeight((int)((34d / 100 * height) - ((22d / 100 * height))));
views.get("ivtrailer").vw.setLeft((int)((10d / 100 * width)));
views.get("ivtrailer").vw.setWidth((int)((16d / 100 * width) - ((10d / 100 * width))));
views.get("ivtrailer").vw.setTop((int)((2d / 100 * height)));
views.get("ivtrailer").vw.setHeight((int)((7d / 100 * height) - ((2d / 100 * height))));
views.get("lbltrailer").vw.setLeft((int)((views.get("ivtrailer").vw.getLeft() + views.get("ivtrailer").vw.getWidth())));
views.get("lbltrailer").vw.setWidth((int)((30d / 100 * width) - ((views.get("ivtrailer").vw.getLeft() + views.get("ivtrailer").vw.getWidth()))));
views.get("lbltrailer").vw.setTop((int)((2d / 100 * height)));
views.get("lbltrailer").vw.setHeight((int)((7d / 100 * height) - ((2d / 100 * height))));
views.get("ivrate").vw.setLeft((int)((views.get("lbltrailer").vw.getLeft() + views.get("lbltrailer").vw.getWidth())+(12d / 100 * width)));
views.get("ivrate").vw.setWidth((int)((50d / 100 * width) - ((views.get("lbltrailer").vw.getLeft() + views.get("lbltrailer").vw.getWidth())+(12d / 100 * width))));
views.get("ivrate").vw.setTop((int)((2d / 100 * height)));
views.get("ivrate").vw.setHeight((int)((7d / 100 * height) - ((2d / 100 * height))));
views.get("lblrat").vw.setLeft((int)((views.get("ivrate").vw.getLeft() + views.get("ivrate").vw.getWidth())));
views.get("lblrat").vw.setWidth((int)((60d / 100 * width) - ((views.get("ivrate").vw.getLeft() + views.get("ivrate").vw.getWidth()))));
views.get("lblrat").vw.setTop((int)((2d / 100 * height)));
views.get("lblrat").vw.setHeight((int)((7d / 100 * height) - ((2d / 100 * height))));
views.get("ivcomment").vw.setLeft((int)((views.get("lblrat").vw.getLeft() + views.get("lblrat").vw.getWidth())+(9d / 100 * width)));
views.get("ivcomment").vw.setWidth((int)((76d / 100 * width) - ((views.get("lblrat").vw.getLeft() + views.get("lblrat").vw.getWidth())+(9d / 100 * width))));
views.get("ivcomment").vw.setTop((int)((2d / 100 * height)));
views.get("ivcomment").vw.setHeight((int)((7d / 100 * height) - ((2d / 100 * height))));
views.get("lblcomment").vw.setLeft((int)((views.get("ivcomment").vw.getLeft() + views.get("ivcomment").vw.getWidth())));
views.get("lblcomment").vw.setWidth((int)((100d / 100 * width) - ((views.get("ivcomment").vw.getLeft() + views.get("ivcomment").vw.getWidth()))));
views.get("lblcomment").vw.setTop((int)((2d / 100 * height)));
views.get("lblcomment").vw.setHeight((int)((7d / 100 * height) - ((2d / 100 * height))));
views.get("lbltitle").vw.setLeft((int)((1d / 100 * width)));
views.get("lbltitle").vw.setWidth((int)((80d / 100 * width) - ((1d / 100 * width))));
views.get("lbltitle").vw.setTop((int)((1d / 100 * height)));
views.get("lbltitle").vw.setHeight((int)((5d / 100 * height) - ((1d / 100 * height))));
views.get("ivaction").vw.setLeft((int)((1d / 100 * width)));
views.get("ivaction").vw.setWidth((int)((8d / 100 * width) - ((1d / 100 * width))));
views.get("ivaction").vw.setTop((int)((views.get("lbltitle").vw.getTop() + views.get("lbltitle").vw.getHeight())+(1d / 100 * height)));
views.get("ivaction").vw.setHeight((int)((10d / 100 * height) - ((views.get("lbltitle").vw.getTop() + views.get("lbltitle").vw.getHeight())+(1d / 100 * height))));
views.get("lblaction").vw.setLeft((int)((views.get("ivaction").vw.getLeft() + views.get("ivaction").vw.getWidth())+(1d / 100 * width)));
views.get("lblaction").vw.setWidth((int)((40d / 100 * width) - ((views.get("ivaction").vw.getLeft() + views.get("ivaction").vw.getWidth())+(1d / 100 * width))));
views.get("lblaction").vw.setTop((int)((views.get("lbltitle").vw.getTop() + views.get("lbltitle").vw.getHeight())+(1d / 100 * height)));
views.get("lblaction").vw.setHeight((int)((10d / 100 * height) - ((views.get("lbltitle").vw.getTop() + views.get("lbltitle").vw.getHeight())+(1d / 100 * height))));
views.get("ivtime").vw.setLeft((int)((1d / 100 * width)));
views.get("ivtime").vw.setWidth((int)((8d / 100 * width) - ((1d / 100 * width))));
views.get("ivtime").vw.setTop((int)((views.get("ivaction").vw.getTop() + views.get("ivaction").vw.getHeight())+(1d / 100 * height)));
views.get("ivtime").vw.setHeight((int)((15d / 100 * height) - ((views.get("ivaction").vw.getTop() + views.get("ivaction").vw.getHeight())+(1d / 100 * height))));
views.get("lbltime").vw.setLeft((int)((views.get("ivtime").vw.getLeft() + views.get("ivtime").vw.getWidth())+(1d / 100 * width)));
views.get("lbltime").vw.setWidth((int)((40d / 100 * width) - ((views.get("ivtime").vw.getLeft() + views.get("ivtime").vw.getWidth())+(1d / 100 * width))));
views.get("lbltime").vw.setTop((int)((views.get("lblaction").vw.getTop() + views.get("lblaction").vw.getHeight())+(1d / 100 * height)));
views.get("lbltime").vw.setHeight((int)((15d / 100 * height) - ((views.get("lblaction").vw.getTop() + views.get("lblaction").vw.getHeight())+(1d / 100 * height))));
views.get("ivgaris").vw.setLeft((int)(0d));
views.get("ivgaris").vw.setWidth((int)((100d / 100 * width) - (0d)));
views.get("ivgaris").vw.setTop((int)((views.get("lbltime").vw.getTop() + views.get("lbltime").vw.getHeight())+(1d / 100 * height)));
views.get("ivgaris").vw.setHeight((int)((18d / 100 * height) - ((views.get("lbltime").vw.getTop() + views.get("lbltime").vw.getHeight())+(1d / 100 * height))));
views.get("lblrate").vw.setLeft((int)((80d / 100 * width)));
views.get("lblrate").vw.setWidth((int)((95d / 100 * width) - ((80d / 100 * width))));
views.get("lblrate").vw.setTop((int)((8d / 100 * height)));
views.get("lblrate").vw.setHeight((int)((views.get("ivgaris").vw.getTop())-(1d / 100 * height) - ((8d / 100 * height))));
views.get("lbldirector").vw.setTop((int)((views.get("ivgaris").vw.getTop() + views.get("ivgaris").vw.getHeight())+(1d / 100 * height)));
views.get("lbldirector").vw.setHeight((int)((22.5d / 100 * height) - ((views.get("ivgaris").vw.getTop() + views.get("ivgaris").vw.getHeight())+(1d / 100 * height))));
views.get("lbldirector").vw.setLeft((int)((1d / 100 * width)));
views.get("lbldirector").vw.setWidth((int)((20d / 100 * width) - ((1d / 100 * width))));
views.get("lbldirec").vw.setTop((int)((views.get("ivgaris").vw.getTop() + views.get("ivgaris").vw.getHeight())+(1d / 100 * height)));
views.get("lbldirec").vw.setHeight((int)((22.5d / 100 * height) - ((views.get("ivgaris").vw.getTop() + views.get("ivgaris").vw.getHeight())+(1d / 100 * height))));
views.get("lbldirec").vw.setLeft((int)((views.get("lbldirector").vw.getLeft() + views.get("lbldirector").vw.getWidth())));
views.get("lbldirec").vw.setWidth((int)((70d / 100 * width) - ((views.get("lbldirector").vw.getLeft() + views.get("lbldirector").vw.getWidth()))));
views.get("lblcast").vw.setTop((int)((views.get("lbldirector").vw.getTop() + views.get("lbldirector").vw.getHeight())+(1d / 100 * height)));
views.get("lblcast").vw.setHeight((int)((27d / 100 * height) - ((views.get("lbldirector").vw.getTop() + views.get("lbldirector").vw.getHeight())+(1d / 100 * height))));
views.get("lblcast").vw.setLeft((int)((1d / 100 * width)));
views.get("lblcast").vw.setWidth((int)((20d / 100 * width) - ((1d / 100 * width))));
views.get("lblnmcast").vw.setTop((int)((views.get("lbldirec").vw.getTop() + views.get("lbldirec").vw.getHeight())+(1d / 100 * height)));
views.get("lblnmcast").vw.setHeight((int)((27d / 100 * height) - ((views.get("lbldirec").vw.getTop() + views.get("lbldirec").vw.getHeight())+(1d / 100 * height))));
views.get("lblnmcast").vw.setLeft((int)((views.get("lblcast").vw.getLeft() + views.get("lblcast").vw.getWidth())));
views.get("lblnmcast").vw.setWidth((int)((70d / 100 * width) - ((views.get("lblcast").vw.getLeft() + views.get("lblcast").vw.getWidth()))));
views.get("lblwrite").vw.setTop((int)((views.get("lblcast").vw.getTop() + views.get("lblcast").vw.getHeight())+(1d / 100 * height)));
views.get("lblwrite").vw.setHeight((int)((32d / 100 * height) - ((views.get("lblcast").vw.getTop() + views.get("lblcast").vw.getHeight())+(1d / 100 * height))));
views.get("lblwrite").vw.setLeft((int)((1d / 100 * width)));
views.get("lblwrite").vw.setWidth((int)((20d / 100 * width) - ((1d / 100 * width))));
views.get("lblnmwrite").vw.setTop((int)((views.get("lblnmcast").vw.getTop() + views.get("lblnmcast").vw.getHeight())+(1d / 100 * height)));
views.get("lblnmwrite").vw.setHeight((int)((32d / 100 * height) - ((views.get("lblnmcast").vw.getTop() + views.get("lblnmcast").vw.getHeight())+(1d / 100 * height))));
views.get("lblnmwrite").vw.setLeft((int)((views.get("lblwrite").vw.getLeft() + views.get("lblwrite").vw.getWidth())));
views.get("lblnmwrite").vw.setWidth((int)((70d / 100 * width) - ((views.get("lblwrite").vw.getLeft() + views.get("lblwrite").vw.getWidth()))));
views.get("lblsynopsis").vw.setTop((int)((views.get("lblwrite").vw.getTop() + views.get("lblwrite").vw.getHeight())+(1d / 100 * height)));
views.get("lblsynopsis").vw.setHeight((int)((36.5d / 100 * height) - ((views.get("lblwrite").vw.getTop() + views.get("lblwrite").vw.getHeight())+(1d / 100 * height))));
views.get("lblsynopsis").vw.setLeft((int)((1d / 100 * width)));
views.get("lblsynopsis").vw.setWidth((int)((30d / 100 * width) - ((1d / 100 * width))));
views.get("lblcerita").vw.setTop((int)((views.get("lblsynopsis").vw.getTop() + views.get("lblsynopsis").vw.getHeight())+(1d / 100 * height)));
views.get("lblcerita").vw.setHeight((int)((100d / 100 * height) - ((views.get("lblsynopsis").vw.getTop() + views.get("lblsynopsis").vw.getHeight())+(1d / 100 * height))));
views.get("lblcerita").vw.setLeft((int)((1d / 100 * width)));
views.get("lblcerita").vw.setWidth((int)((100d / 100 * width) - ((1d / 100 * width))));

}
}